'use client';
import {useEffect,useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowDownRight,ArrowUpRight,Github,Linkedin,Mail,Menu,Moon,Sparkles,Sun,X} from 'lucide-react';

const projects=[
['MySpeakScore','AI-powered speaking coach that analyzes presentations and delivers personalized feedback.',['AI Coaching','OpenAI','Whisper'],'https://app.myspeakscore.ai','#c9ff47'],
['Study Buddy','An all-in-one e-learning platform for students and instructors.',['Next.js','MySQL','React'],null,'#7dd3fc'],
['KAIRON Meeting Assistant','A meeting companion with real-time transcription and AI-generated responses.',['Python','PyQt','OpenAI'],null,'#a78bfa'],
['VegMart','A full ecommerce marketplace connecting grocery customers with vendors.',['React','MongoDB','Node.js'],null,'#86efac'],
['Makergrid.ai','AI-powered 3D generation from prompts, images, and sketches.',['Next.js','OpenAI','3D AI'],'https://www.makergrid.ai/','#f0abfc'],
['SoulTalk','An empathetic AI therapist experience with conversational avatars.',['React','OpenAI','D-ID'],null,'#fda4af'],
['SaleAICE.AI','An autonomous AI sales agent for the journey from prospecting to close.',['Next.js','OpenAI','Hume AI'],'https://www.salesaice.ai/','#fb923c'],
['Multimodal AI Chatbot','A desktop assistant combining GPT, image generation, and speech.',['GPT-4','DALL·E','Whisper'],null,'#818cf8'],
['Coding The Brains Interactive','An education platform with a browser IDE and AI code mentoring.',['Django','AI Mentoring','IDE'],null,'#38bdf8'],
['AI Health Coach','Mood-aware guidance delivered through an AI-generated Scottish voice.',['Next.js','Flask','ElevenLabs'],null,'#2dd4bf'],
['Analyzify','AI-powered SEO reports with practical recommendations for visibility.',['React','TypeScript','AI SEO'],null,'#facc15'],
['Frost Trek','A platform for generating, editing, and sharing AI artwork.',['React','OpenAI','MongoDB'],null,'#bae6fd'],
['Stingrai','A multi-portal penetration-testing workflow platform.',['Next.js','GraphQL','Socket.io'],'https://www.stingrai.io/','#fb7185'],
['Remote Bridge','A responsive hiring platform connecting recruiters and candidates.',['Next.js','UX Design','Responsive'],null,'#93c5fd'],
['Reviaw','AI shopping comparisons with product-level sustainability insights.',['AI Analytics','Node.js','MongoDB'],null,'#4ade80'],
['VaxSupport','An AI chatbot providing contextual answers to vaccination questions.',['Next.js','MERN','AI Chatbot'],'https://vaccifi.co/','#67e8f9'],
['TikTok Shop Monitoring Bot','Product monitoring with configurable tasks and Telegram alerts.',['Python','Selenium','PyQt6'],null,'#f472b6'],
['AI Used Car Price Predictor','Machine learning that predicts used-car prices from market data.',['Machine Learning','Django','KNN'],null,'#fbbf24'],
['AI Shopping Search Engine','ML-powered classification of trustworthy shopping results.',['Python','PyQt','ML'],null,'#c4b5fd'],
['LinkedIn Connections Finder','Automated discovery of mutual connections across prospect lists.',['Selenium','Automation','Python'],null,'#60a5fa'],
['Neural Network Trainer','A visual tool for training and evaluating classification models.',['Neural Networks','Python','Data Science'],null,'#a3e635'],
['Face Unlock Cabinet','IoT security combining facial recognition, AWS, and hardware.',['Computer Vision','AWS IoT','Raspberry Pi'],null,'#f97316'],
['Contact Bot AI','Automated business discovery and personalized AI outreach.',['Django','Selenium','OpenAI'],null,'#e879f9'],
['AI BoreScope','An inspection robot using deep learning to detect pipeline defects.',['Robotics','Deep Learning','Vision AI'],null,'#22d3ee'],
['HFX Calculator','A focused toolkit for forex position and risk calculations.',['Fintech','Web App'],'https://www.hfxcalculator.com/','#d9ff69'],
['Di Lusso Beds','A polished ecommerce experience for handcrafted luxury beds.',['Ecommerce','UX/UI'],'https://www.dilussobeds.co.uk','#e3c4a7'],
['Silver Halo','Premium digital storefront with an editorial, product-first feel.',['Ecommerce','Branding'],'https://www.silver-halo.com','#cbd5e1'],
['Nobu Beds','Contemporary bed shopping made tactile, simple, and inviting.',['Ecommerce','Web Design'],'https://www.nobubeds.co.uk','#ffac8e'],
['Arizon City','A bold property platform built to make discovery feel effortless.',['Property','Development'],'https://www.arizoncity.com','#ffda57'],
['Allied Housing Solutions','A trustworthy digital home for supported housing services.',['Housing','Web Design'],'https://www.alliedhousingsolutions.com','#8bd9c7'],
['Tech Locker','A sharp ecommerce destination for accessible everyday tech.',['Technology','Ecommerce'],'https://www.tech-locker.com','#99baff'],
['SM Mortgages','Friendly mortgage guidance presented with clarity and confidence.',['Finance','Lead Gen'],'https://www.smmortgages.co.uk','#9ad6ff'],
['Chrysalis Care & Mentoring','A warm, human website for care and mentoring support.',['Care','Web Design'],'https://www.chrysaliscarementoring.com','#c2a7f2'],
['Xinchi','A streamlined hiring platform designed around better matches.',['Recruitment','Platform'],'https://www.xinchire.com','#ff9f7f'],
['Elite Auto Hire','Premium vehicle hire brought to life through a cinematic interface.',['Automotive','Booking'],'https://www.eliteautohire.co.uk','#f4d35e'],
['Chic & Posh Lounge','A personality-rich home for beauty and lifestyle services.',['Beauty','Bookings'],'https://www.chicandposhlounge.com','#f6a6c1'],
['Xtreme Pharmacy','A fast, accessible digital pharmacy experience for everyday care.',['Healthcare','Ecommerce'],'https://www.xtremepharmacy.co.uk','#8fe3cf'],
['My Home Grants','An approachable site that simplifies access to home funding.',['Energy','Lead Gen'],'https://www.myhomegrants.co.uk','#b8e986'],
['Pass Me 1st','An upbeat driving school platform built to turn visits into lessons.',['Education','Bookings'],'https://www.passme1st.co.uk','#ffdf6c'],
['Daya Solution','A clean business website that makes complex services feel simple.',['B2B','Development'],'https://www.dayasolution.com','#7fc8f8'],
['The IP Centre','An authoritative destination for intellectual property expertise.',['Legal','Content'],'https://www.theipcentre.com','#a3b8ff'],
['The IM Centre','A focused platform for innovation management services.',['Consulting','Web Design'],'https://www.theimcentre.com','#d2b7ff'],
['Dermalogic Aesthetics','A refined clinic experience balancing credibility and beauty.',['Aesthetics','Bookings'],'https://www.dermalogicaesthetics.com','#eab8c0'],
['Skyways Executive Travel','Executive transport presented with quiet, premium confidence.',['Travel','Bookings'],'https://www.skywaysexecutivetravel.co.uk','#a9c9ff'],
['Supernet Pharmacy','Convenient healthcare and pharmacy services in one accessible hub.',['Healthcare','Web App'],'https://www.supernetpharmacy.co.uk','#78dcca'],
['Lime Pickle','A flavourful takeaway experience built for quick online ordering.',['Restaurant','Ordering'],'https://www.limepickleindiantakeaway.co.uk','#cfff65'],
['Smallest Mobile Phones','A niche ecommerce store with a playful, conversion-led experience.',['Mobile','Ecommerce'],'https://www.smallestmobilephones.co.uk','#9ca7ff'],
['Plumb Safe','A dependable local services site designed for fast customer action.',['Trades','Lead Gen'],'https://www.plumb-safe.co.uk','#75c8ff'],
['Kay Ali MUA','An elegant portfolio and booking home for a makeup artist.',['Beauty','Portfolio'],'https://www.kayalimua.co.uk','#f5b7b1']];
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-70px'},transition:{duration:.65,ease:[.22,1,.36,1]}};

function Toggle({dark,setDark}){return <button aria-label="Toggle color theme" onClick={()=>setDark(!dark)} className="grid h-10 w-10 place-items-center rounded-full border border-current/20 transition hover:bg-black/5 dark:hover:bg-white/10">{dark?<Sun size={17}/>:<Moon size={17}/>}</button>}
function Visual({name,index,color,live}){return <div className="relative aspect-[16/10] overflow-hidden p-5" style={{background:`linear-gradient(145deg,${color} 0%,${color}bb 45%,#171714 45.2%)`}}><div className="absolute inset-x-5 top-5 flex justify-between text-[9px] font-bold uppercase tracking-[.18em] text-ink/70"><span>Fuchesi / {String(index+1).padStart(2,'0')}</span><span>{live?'Live project':'Private build'}</span></div><div className="absolute bottom-5 left-5 right-5 rounded-lg border border-white/15 bg-black/70 p-4 text-white shadow-2xl backdrop-blur-sm"><div className="mb-3 flex gap-1.5"><i className="h-1.5 w-1.5 rounded-full bg-white/40"/><i className="h-1.5 w-1.5 rounded-full bg-white/25"/><i className="h-1.5 w-1.5 rounded-full bg-white/15"/></div><p className="font-serif text-xl leading-none">{name}</p><div className="mt-3 h-1 w-2/3 rounded bg-white/20"/><div className="mt-1.5 h-1 w-1/2 rounded bg-white/10"/></div></div>}

export default function Portfolio(){
 const[dark,setDark]=useState(true),[menu,setMenu]=useState(false),[showAll,setShowAll]=useState(false);
 useEffect(()=>{const s=localStorage.getItem('theme');const n=s?s==='dark':true;setDark(n);document.documentElement.classList.toggle('dark',n)},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 const visible=showAll?projects:projects.slice(0,9);
 return <main className="grain overflow-hidden">
 <header className="fixed inset-x-0 top-0 z-40 border-b border-black/10 bg-paper/80 backdrop-blur-xl dark:border-white/10 dark:bg-ink/80"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" className="text-lg font-extrabold tracking-[-.05em]">FUCHESI<span className="text-acid">.</span></a><nav className="hidden items-center gap-8 text-xs font-bold uppercase tracking-[.16em] md:flex">{['Projects','About','Skills','Contact'].map(x=><a key={x} className="transition hover:text-lime-600 dark:hover:text-acid" href={'#'+x.toLowerCase()}>{x}</a>)}</nav><div className="flex items-center gap-2"><Toggle dark={dark} setDark={setDark}/><button onClick={()=>setMenu(!menu)} className="grid h-10 w-10 place-items-center md:hidden" aria-label="Open menu">{menu?<X/>:<Menu/>}</button></div></div><AnimatePresence>{menu&&<motion.nav initial={{height:0}} animate={{height:'auto'}} exit={{height:0}} className="overflow-hidden border-t border-current/10 bg-paper dark:bg-ink md:hidden"><div className="flex flex-col px-5 py-5">{['Projects','About','Skills','Contact'].map(x=><a key={x} onClick={()=>setMenu(false)} className="py-3 text-lg font-bold" href={'#'+x.toLowerCase()}>{x}</a>)}</div></motion.nav>}</AnimatePresence></header>
 <section id="top" className="relative flex min-h-screen items-end border-b border-current/10 px-5 pb-14 pt-32 lg:px-8 lg:pb-20"><div className="pointer-events-none absolute -right-28 top-20 h-96 w-96 rounded-full bg-acid/15 blur-[100px]"/><div className="mx-auto w-full max-w-7xl"><motion.div initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.7}} className="mb-8 flex items-center gap-3 text-xs font-bold uppercase tracking-[.2em]"><span className="h-2 w-2 animate-pulse rounded-full bg-acid ring-4 ring-acid/20"/>Independent digital studio · Worldwide</motion.div><h1 className="max-w-6xl text-[clamp(3.8rem,11vw,9.6rem)] font-extrabold leading-[.83] tracking-[-.075em]">We build digital<br/><span className="font-serif font-normal italic tracking-[-.045em] text-lime-600 dark:text-acid">things that work.</span></h1><div className="mt-10 grid gap-8 md:grid-cols-2 md:items-end"><p className="max-w-xl text-base leading-7 text-black/65 dark:text-white/65 md:text-lg">Fuchesi is Umer and Farees — a two-person studio turning ambitious ideas into sharp websites, AI automation tools, and mobile products.</p><div className="flex gap-3 md:justify-end"><a href="#projects" className="flex items-center gap-2 rounded-full bg-ink px-6 py-3.5 text-sm font-bold text-paper transition hover:-translate-y-1 dark:bg-acid dark:text-ink">View projects <ArrowDownRight size={17}/></a><a href="#contact" className="rounded-full border border-current/25 px-6 py-3.5 text-sm font-bold">Contact us</a></div></div></div></section>
 <section id="projects" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="mb-14 flex flex-col justify-between gap-6 border-b border-current/15 pb-8 md:flex-row md:items-end"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.22em] text-lime-700 dark:text-acid">Selected work</p><h2 className="font-serif text-5xl tracking-tight md:text-7xl">Built to be used.</h2></div><p className="max-w-sm text-sm leading-6 text-black/55 dark:text-white/55">Digital experiences across commerce, healthcare, property, finance, and beyond.</p></motion.div><motion.div layout className="project-grid grid gap-5">{visible.map((p,i)=><motion.article layout {...reveal} key={p[0]} className="group overflow-hidden rounded-2xl border border-current/10 bg-white/50 transition duration-300 hover:-translate-y-1 hover:shadow-2xl dark:bg-white/[.035]"><Visual name={p[0]} index={i} color={p[4]} live={Boolean(p[3])}/><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-extrabold tracking-tight">{p[0]}</h3>{p[3]?<a href={p[3]} target="_blank" rel="noreferrer" aria-label={'Visit '+p[0]} className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-current/15 transition group-hover:rotate-45 group-hover:bg-acid group-hover:text-ink"><ArrowUpRight size={17}/></a>:<span className="rounded-full border border-current/10 px-3 py-1.5 text-[9px] font-bold uppercase tracking-wider text-black/40 dark:text-white/40">Private project</span>}</div><p className="mt-3 min-h-12 text-sm leading-6 text-black/55 dark:text-white/55">{p[1]}</p><div className="mt-5 flex flex-wrap gap-2">{p[2].map(t=><span key={t} className="rounded-full border border-current/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider">{t}</span>)}</div></div></motion.article>)}</motion.div><div className="mt-10 flex justify-center"><button onClick={()=>setShowAll(!showAll)} className="rounded-full border border-current/20 px-7 py-3 text-sm font-bold transition hover:bg-acid hover:text-ink">{showAll?'Show selected work':`View all ${projects.length} projects`}</button></div></div></section>
 <section id="about" className="border-y border-current/10 bg-black/[.03] px-5 py-24 dark:bg-white/[.025] lg:px-8 lg:py-32"><motion.div {...reveal} className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-lime-700 dark:text-acid">About Fuchesi</p><div className="mt-8 grid h-28 w-28 place-items-center rounded-full border border-current/15"><Sparkles className="text-lime-600 dark:text-acid" size={38}/></div></div><div><h2 className="font-serif text-4xl leading-[1.05] tracking-tight md:text-6xl">Part sales instinct.<br/>Part engineering obsession.<br/><em className="text-lime-700 dark:text-acid">All-in on useful ideas.</em></h2><div className="mt-10 grid gap-6 text-base leading-7 text-black/60 dark:text-white/60 md:grid-cols-2"><p>We’re Farees and Umer, the partners behind Fuchesi. With a background in AI and computer science, we blend technical depth with a practical understanding of what helps a business grow.</p><p>Right now we’re focused on AI automation, thoughtful mobile apps, and digital products that remove friction. No inflated process — just close collaboration and work we’re proud to put our names on.</p></div></div></motion.div></section>
 <section id="skills" className="px-5 py-24 lg:px-8 lg:py-32"><motion.div {...reveal} className="mx-auto max-w-7xl"><p className="mb-8 text-xs font-bold uppercase tracking-[.22em] text-lime-700 dark:text-acid">What we do</p><div className="divide-y divide-current/15 border-y border-current/15">{[['01','AI automation','Agents, workflows, integrations'],['02','Web experiences','Strategy, design, development'],['03','Mobile products','Useful apps, built with intent'],['04','Growth systems','Sales flows, funnels, conversion']].map(r=><div key={r[0]} className="group grid gap-3 py-7 md:grid-cols-[80px_1fr_1fr] md:items-center"><span className="text-xs font-bold text-black/35 dark:text-white/35">{r[0]}</span><h3 className="text-2xl font-extrabold tracking-tight transition group-hover:translate-x-2 md:text-4xl">{r[1]}</h3><p className="text-sm text-black/50 dark:text-white/50 md:text-right">{r[2]}</p></div>)}</div></motion.div></section>
 <section id="contact" className="bg-acid px-5 py-24 text-ink lg:px-8 lg:py-32"><motion.div {...reveal} className="mx-auto max-w-7xl"><p className="mb-8 text-xs font-bold uppercase tracking-[.22em]">Have an idea?</p><div className="grid gap-12 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-4xl text-[clamp(3.2rem,9vw,8rem)] font-extrabold leading-[.84] tracking-[-.07em]">Let’s make it<br/><span className="font-serif font-normal italic">real.</span></h2><div className="mt-10 flex flex-col items-start gap-3"><a href="mailto:fareesfatima.arain@gmail.com" className="inline-flex items-center gap-3 border-b-2 border-ink pb-2 text-lg font-bold">fareesfatima.arain@gmail.com <ArrowUpRight/></a><a href="https://wa.me/971559656975" target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 border-b-2 border-ink pb-2 text-lg font-bold">+971 55 965 6975 <ArrowUpRight/></a></div></div><div className="flex gap-3" aria-label="Social profiles coming soon"><button type="button" disabled aria-label="LinkedIn profile coming soon" title="Coming soon" className="grid h-12 w-12 cursor-not-allowed place-items-center rounded-full border border-ink/20 opacity-45"><Linkedin size={19}/></button><button type="button" disabled aria-label="GitHub profile coming soon" title="Coming soon" className="grid h-12 w-12 cursor-not-allowed place-items-center rounded-full border border-ink/20 opacity-45"><Github size={19}/></button><button type="button" disabled aria-label="Email shortcut coming soon" title="Coming soon" className="grid h-12 w-12 cursor-not-allowed place-items-center rounded-full border border-ink/20 opacity-45"><Mail size={19}/></button></div></div></motion.div></section>
 <footer className="bg-ink px-5 py-7 text-paper lg:px-8"><div className="mx-auto max-w-7xl text-xs text-white/50"><p>© {new Date().getFullYear()} Fuchesi. Built with intent.</p></div></footer>
 </main>
}
