import shots from '@/content/shots.json';

/**
 * Screenshot manifest, generated by `npm run shots` (scripts/capture-shots.mjs).
 *
 * Intrinsic width/height are recorded at capture time and passed to next/image
 * so every card reserves its exact box before the image loads — that is what
 * keeps CLS at zero on a grid of 49 of them.
 */
export type Shot = {
  src: string;
  width: number;
  height: number;
  /** ISO date of capture — these are live sites and will drift. */
  capturedAt: string;
};

const manifest = shots as Record<string, Shot>;

export const getShot = (slug: string): Shot | null => manifest[slug] ?? null;
